apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
#- prometheus-sa.yaml
- prometheus-package-install.yaml
vars:
- name: cluster_name
  objref:
    kind: Secret
    name: cluster-name-secret
    apiVersion: v1
  fieldref:
    fieldpath: data.cluster_name
secretGenerator:
- name: prometheus-packages-values
  namespace: packages
  files:
  - prometheus-data-values.yaml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: prometheus-packages
- name: alertmanager-overlay
  namespace: packages
  files:
  - overlay-alertmanager.yaml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: prometheus-packages
