apiVersion: crd.antrea.io/v1alpha1
kind: NetworkPolicy
metadata:
  name: test-nginx
  namespace: packages
spec:
    priority: 100
    tier: securityops
    appliedTo:
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: my-release
    ingress:
      - action: Allow
        from:
          - podSelector:
              matchLabels:
                run: dnstools
            namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: test
        ports:
          - protocol: TCP
            port: 80
          - protocol: TCP
            port: 8080
        name: AllowFromFrontend
        enableLogging: false
