apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
 disableNameSuffixHash: true

secretGenerator:
- name: fluentbit-data-values
  namespace: packages
  files:
  - fluent-secret.yaml
resources:
- fluentd-bit.yaml
