apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 1m
  chart:
    spec:
      chart: falcosecurity/falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: tanzu-helm-resources
      interval: 1m
#  valuesFrom:
#  - kind: ConfigMap
#    name: helmvalue

