apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 1m
  chart:
    spec:
      chart: falco
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: tanzu-helm-resources
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: helmvalue

