apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrepository.yaml
- helmrelease.yaml
configMapGenerator:
- name: helmvalue
  namespace: tanzu-helm-resources
  files:
  - values.yaml
