apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- helmrepository.yaml
- helmrelease.yaml
configMapGenerator:
- name: helmvalue
  namespace: falco
  files:
  - values.yaml
