image:
  pullPolicy: IfNotPresent
  registry: artifactory.dev.e2open.com
  repository: docker/docker.io/falcosecurity/falco-no-driver
  tag: "0.33.1"

imagePullSecrets:
 - name: regcred

driver:
  loader:
    initContainer:
      image:
        pullPolicy: IfNotPresent
        registry: artifactory.dev.e2open.com
        repository: docker/docker.io/falcosecurity/falco-driver-loader
        tag: "0.33.1"

