apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- external-secrets-ns.yaml
- falco-ns.yaml
- fluentd-ns.yaml
- ing-nginx-ns.yaml
- monitor-logging-ns.yaml
- packages-ns.yaml
- prometheus-ns.yaml
- tanzu-terraform-controller-ns.yaml
- trident-ns.yaml
transformers:
    - global-labels.yaml

