apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: nginx-ingress
spec:
  chart:
    spec:
      version: "4.0.18"
  test:
    enable: true
  values:
    controller:
      name: controller
      image:
        registry: artifactory.dev.e2open.com
        image: docker/k8s.gcr.io/ingress-nginx/controller
        tag: "v1.1.2"
        digest: sha256:6a18680809f9bdf7bba4092cede2b5f3ee3566fb65c1bf4cfce328c5ee94bac7

      replicaCount: 3
    imagePullSecrets:
    - name: regcred

