apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: ${cluster_name}
          role: common-secrets
          serviceAccountRef:
            name: vault-auth
      caProvider:
        key: vault-ca.crt
        name: vault-ca
        namespace: kube-public
        type: ConfigMap
      path: common-secrets
      server: https://vault.dev.e2open.com
      version: v2

