---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trident-operator
  namespace: trident
  labels:
    app: operator.trident.netapp.io
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: trident
secrets:
- name: vault-auth-token
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-token
  namespace: external-secrets
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token


