apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  tridentImage: artifactory.dev.e2open.com/dcops-docker-repo/trident:23.07.1
  imagePullSecrets:
  - regcred
