---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secret-operator
  namespace: tanzu-continuousdelivery-resources
spec:
#  dependsOn:
#    - name: tanzu-packages-serviceaccounts
#    - name: tanzu-packages-namespaces
#    - name: tanzu-packages-package-repo
  interval: 1m0s
  path: ./dev/post-install/external-secret-operator
  prune: true
#  patches:
#    - patch: |-
#        apiVersion: trident.netapp.io/v1
#        kind: TridentBackendConfig
#        metadata:
#          name: not-used
#        spec:
#          backendName: inlinestr8fromkustomize
#    - patch: |-
#        - op: replace
#          path: /spec/defaults/spaceReserve
#          value: ${cluster_name}
#
#      target:
#        kind: TridentBackendConfig
#        name: ontap-nas
#        namespace: trident
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-name-secret
  sourceRef:
    kind: GitRepository
    name: base-packages
    namespace: tanzu-continuousdelivery-resources
