---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-nginx-ingress
  namespace: tanzu-continuousdelivery-resources
spec:
#  dependsOn:
#    - name: helm-nginx-ingress-sa
#    - name: tanzu-packages-package-repo
  interval: 1m0s
  path: ./dev/post-install/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: base-packages
    namespace: ingress-nginx
#  healthChecks:
#    - apiVersion: apps/v1
#      kind: Deployment
#      name: ingress-nginx
#      namespace: ingress-nginx



