---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-falco
  namespace: tanzu-continuousdelivery-resources
spec:
#  dependsOn:
#    - name: tanzu-packages-serviceaccounts
#    - name: tanzu-packages-namespaces
#    - name: tanzu-packages-package-repo
  interval: 1m0s
  path: ./dev/post-install/falco
  prune: true
  sourceRef:
    kind: GitRepository
    name: base-packages
    namespace: tanzu-continuousdelivery-resources
