apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- psp.yaml
- external-secret-operator-install.yaml
- tanzu-packages-vault.yaml
- clustersecretstore.yaml
- tanzu-packages-cert-manager.yaml
- tanzu-packages-prometheus.yaml
- helm-ingress-nginx.yaml
- tanzu-packages-contour.yaml
- tanzu-packages-fluent-bit.yaml
- trident-install.yaml
- helm-falco.yaml
#- tanzu-terraform.yaml
transformers:
    - global-labels.yaml
