apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tanzu-packages-cert-manager.yaml
- psp.yaml
- helm-ingress-nginx.yaml
#- tanzu-packages-contour.yaml
- tanzu-packages-fluent-bit.yaml
- tanzu-packages-vault.yaml
- trident-install.yaml
#- tanzu-packages-grafana.yaml
#- tanzu-packages-harbor.yaml
#- tanzu-packages-prometheus.yaml
#- tanzu-terraform.yaml
transformers:
    - global-labels.yaml
replacements: 
- source:
    kind: Secret 
    name: cluster-name-secret
    namespace: trident 
    fieldPath: data.cluster_name
  targets:
  - select: 
      name: ontap-nas
      kind: TridentBackendConfig
      namespace: trident
      fieldPaths: spec.svm
