---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-fluentd-bit
  namespace: tanzu-continuousdelivery-resources
spec:
#  dependsOn:
#    - name: tanzu-packages-cert-manager-sa
#    - name: tanzu-packages-package-repo
  interval: 1m0s
  path: ./dev/post-install/fluentd-bit
  prune: true
  sourceRef:
    kind: GitRepository
    name: base-packages
    namespace: tanzu-continuousdelivery-resources
#  healthChecks:
#    - apiVersion: apps/v1
#      kind: Daemonset
#      name: fluent-bit
#      namespace: monitor-logging

