---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-prometheus
  namespace: tanzu-continuousdelivery-resources
spec:
#  dependsOn:
#    - name: prometheus-packages-sa
  interval: 1m0s
  path: ./dev/post-install/prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: base-packages
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus-server
      namespace: k8smonitor



