---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-prometheus
  namespace: tanzu-continuousdelivery-resources
spec:
#  dependsOn:
#    - name: prometheus-packages-sa
  interval: 1m0s
  path: ./dev/post-install/prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: base-packages
    namespace: tanzu-continuousdelivery-resources
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-name-secret

  patches:
      - patch: |-
          - op: replace
            path: /data/prometheus/config/prometheus_yml/external_labels/cluster
            value: ${cluster_name}

        target:
          kind: secret
          name: prometheus-packages-values
          namespace: packages



