apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: terraform-demo
  namespace: tanzu-terraform-controller
spec:
#  dependsOn:
#    - name: tanzu-packages-serviceaccounts
#    - name: tanzu-packages-namespaces
#    - name: tanzu-packages-package-repo
  interval: 1m0s
  path: ./dev/post-install/terraform
  approvePlan: "auto"
  sourceRef:
    kind: GitRepository
    name: base-packages
    namespace: tanzu-continuousdelivery-resources
