---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-prometheus
  namespace: tanzu-continuousdelivery-resources
spec:
#  dependsOn:
    - name: tanzu-packages-serviceaccounts
#    - name: tanzu-packages-namespaces
#    - name: tanzu-packages-package-repo
  interval: 1m0s
  path: ./dev/post-install/prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: base-packages
    namespace: tanzu-continuousdelivery-resources
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-name-secret
