---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-vault-register 
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./dev/post-install/vault 
  prune: true
  sourceRef:
    kind: GitRepository
    name: base-packages
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: apps/v1
      kind: pod 
      name: vault
      namespace: external-secrets 

