---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: trident-crd
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./dev/post-install/trident-crds/
  prune: true
#  patches:
#    - patch: |-
#        apiVersion: trident.netapp.io/v1
#        kind: TridentBackendConfig
#        metadata:
#          name: not-used
#        spec:
#          backendName: inlinestr8fromkustomize
#    - patch: |-
#        - op: replace
#          path: /spec/defaults/spaceReserve
#          value: ${cluster_name}
#
#      target:
#        kind: TridentBackendConfig
#        name: ontap-nas
#        namespace: trident
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-name-secret
  sourceRef:
    kind: GitRepository
    name: base-packages
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: trident-controller
      namespace: trident 
