---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: workload-namespace-creation
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-serviceaccounts
    - name: tanzu-packages-namespaces
    - name: clustersecretstore
  interval: 1m0s
  path: ./dev/workload/${cluster_name}
  prune: true
  sourceRef:
    kind: GitRepository
    name: base-packages
    namespace: tanzu-continuousdelivery-resources
