---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: external-secrets-admin-privileged-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:vmware-system-privileged
subjects:
- kind: ServiceAccount
  name: external-secrets-operator
  namespace: external-secrets
- kind: ServiceAccount
  name: external-secrets-cert-controller
  namespace: external-secrets
- kind: ServiceAccount
  name: external-secrets-webhook
  namespace: external-secrets

