---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trident-controller
  namespace: trident
  labels:
    app: controller.csi.trident.netapp.io
subjects:
  - kind: ServiceAccount
    name: trident-controller
    apiGroup: ""
roleRef:
  kind: Role
  name: trident-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trident-controller-psp
  namespace: trident
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:vmware-system-privileged
subjects:
- kind: ServiceAccount
  name: trident-controller
  namespace: trident
