---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trident-node-linux
  namespace: trident
  labels:
    app: node.csi.trident.netapp.io
    kubectl.kubernetes.io/default-container: trident-main
subjects:
  - kind: ServiceAccount
    name: trident-node-linux
    apiGroup: ""
roleRef:
  kind: Role
  name: trident-node-linux
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trident-node-linux-psp
  namespace: trident
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:vmware-system-privileged
subjects:
- kind: ServiceAccount
  name: trident-node-linux
  namespace: trident

