certificates:
  duration: 8760h
  renewBefore: 360h
contour:
  logLevel: info
  replicas: 2
  useProxyProtocol: false
envoy:
  hostNetwork: false
  hostPorts:
    enable: true
    http: 80
    https: 443
  logLevel: info
  service:
      type: LoadBalancer
  terminationGracePeriodSeconds: 300
infrastructure_provider: vsphere
namespace: tanzu-system-ingress
