apiVersion: v1
data:
  VAULT_APPROLE_ROLE_ID: YzQxMzBjMjktMTZmOS1hNzM4LTk3MGQtYmQ4OGVmODg1NTU1
  VAULT_APPROLE_SECRET_ID: ZjVkNDcyM2YtMTMxYi1mODA5LTM4NjMtODY5YTA4ZDE5ZDJk
kind: Secret
metadata:
  creationTimestamp: null
  name: vault-auth-enabler-token
  namespace: external-secrets
