apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: vault
  name: vault
  namespace: external-secrets
spec:
  containers:
  - image: vault:1.7.2
    name: vault
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
