apiVersion: builtin
kind: LabelTransformer
metadata:
  name: global-labels
labels:
 environment: production
 app: my-app
 team: dev-team
 project: my-project
 owner: john-doe
fieldSpecs:
- path: metadata/labels
  create: true
