apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tanzu-packages-namespaces.yaml
- tanzu-packages-serviceaccounts.yaml
- cluster-name-secret.yaml
transformers:
    - global-labels.yaml
