---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: trident
secrets:
- name: vault-auth-token
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-token
  namespace: trident 
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token

---

