apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  trident-secret
  namespace: trident
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name:  backend-tbc-ontap-nas-advanced-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: common-secrets/common-secrets/trident-creds
