apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: regcred
spec:
  externalSecretName: regcred
  externalSecretSpec:
    data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/pullsecret
        property: dockerconfigjson
      secretKey: .dockerconfigjson
    refreshInterval: 1m
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: regcred
      template:
        engineVersion: v2
        type: kubernetes.io/dockerconfigjson
  namespaceSelector:
        matchExpressions:
        - key: name
          operator: NotIn
          values:
          - kube-system
          - kube-public
          - vmware-system-tmc
          - vmware-system-csi
          - vmware-system-cloud-provider
          - vmware-system-auth
          - velero-vsphere-plugin-backupdriver
          - kube-node-lease
          - tanzu-system

  refreshTime: 1m
