---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: input-resource-reader
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: input-resource-reader
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: input-resource-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: input-resource-reader
subjects:
- kind: ServiceAccount
  name: input-resource-reader

---
apiVersion: v1
items:
- apiVersion: secretgen.carvel.dev/v1alpha1
  kind: SecretTemplate
  metadata:
    labels:
    name: kubeadm-config
    namespace: kube-system
  spec:
    inputResources:
    - name: config
      ref:
        apiVersion: v1
        kind: ConfigMap
        name: kubeadm-config
    serviceAccountName: input-resource-reader
    template:
      stringData:
        data: $(.config.data.ClusterConfiguration)
      type: generic
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: kubeadm-config
  namespace: kube-system
spec:
  toNamespace: external-secrets
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: kubeadm-config
  namespace: external-secrets
spec:
    fromNamespace: kube-system
