---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: regcred
  namespace: trident 
spec:
  fromNamespace: default
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: regcred
  namespace: external-secrets
spec:
  fromNamespace: default
---

